### ISSUE TITLE
Can't pull backtest trades 

### ISSUE THREAD

**Issue by johnsonryan** [elsen-trading/elsen-python#1]
Backtest ID: 0e3aa678-cf60-4d15-9b8d-c20789b90824

When running the ID above for `backtest.trades()` in the iPython Notebook.

```
---------------------------------------------------------------------------
JavascriptException                       Traceback (most recent call last)
<ipython-input-15-20c40b513cc6> in <module>()
----> 1 backtest.trades()

/Users/marissaherrman/elsen-python/elsen/elsen.pyc in trades(self, trades)
    476         }
    477         response = self._parent._get("backtests", item=self.id + "/trades",
--> 478                                      request=request)
    479         return Trades(self._parent, response)
    480 

/Users/marissaherrman/elsen-python/elsen/elsen.pyc in _get(self, endpoint, item, request, token)
     99 
    100         if response.status_code != 200:
--> 101             raise JavascriptException("Server exception: " + response.text)
    102         else:
    103             return response.json()

JavascriptException: Server exception: TypeError: Object b.id=&#39;undefined&#39; has no method &#39;join&#39;<br> &nbsp; &nbsp;at /webapp/api/db/backtests.js:1009:7<br> &nbsp; &nbsp;at /webapp/node_modules/pg/lib/pool.js:77:9<br> &nbsp; &nbsp;at dispense (/webapp/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:250:16)<br> &nbsp; &nbsp;at Object.me.acquire (/webapp/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:319:5)<br> &nbsp; &nbsp;at Object.pool.connect (/webapp/node_modules/pg/lib/pool.js:71:12)<br> &nbsp; &nbsp;at PG.connect (/webapp/node_modules/pg/lib/index.js:49:8)<br> &nbsp; &nbsp;at exports.v1_getBacktestsByIdTrades (/webapp/api/db/backtests.js:980:6)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/webapp/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at next (/webapp/node_modules/express/lib/router/route.js:110:13)<br> &nbsp; &nbsp;at null.callback (/webapp/api/db/events.js:95:12)
```

**Comment by sdiehl** [comment]
Should report this on the api tracker, nothing we can do about ``JavascriptException`` in the Python library.

**Comment by justinwhite** [comment]
Think the actual issue occurs when `tradecount` == 0 as seen here:
```
    print backtest.trades().to_dataframe()
```
resulting in 
```
---------------------------------------------------------------------------
JavascriptException                       Traceback (most recent call last)
<ipython-input-21-19a65b8bf280> in <module>()
     16     print backtest.details().get('backtest').get('tradecount')
     17 
---> 18     print backtest.trades().to_dataframe()
     19     if len( backtest.trades().to_dataframe() ) <= 0: continue
     20 

/home/deploy/anaconda/lib/python2.7/site-packages/elsen/elsen.pyc in trades(self, trades)
    476         }
    477         response = self._parent._get("backtests", item=self.id + "/trades",
--> 478                                      request=request)
    479         return Trades(self._parent, response)
    480 

/home/deploy/anaconda/lib/python2.7/site-packages/elsen/elsen.pyc in _get(self, endpoint, item, request, token)
     99 
    100         if response.status_code != 200:
--> 101             raise JavascriptException("Server exception: " + response.text)
    102         else:
    103             return response.json()

JavascriptException: Server exception: No backtest found
```

**Comment by justinwhite** [comment]
https://github.com/elsen-trading/api/issues/148 will fix this by returning an empty array instead of a NULL object.
